### ISSUE TITLE
Improve timer logic

### ISSUE THREAD

**Issue by forginater** [forginater/pom_rust#10]
### TODO
- [ ] Fix: When exit terminal due to panic, stays in raw mode 
- [ ] Remove buffer message in get_num_from_terminal
- [ ] Make timer loop iteration 1s after reaching 0 remaining

> Could make pause polling more responsive by shortening loop iterations into 100ms and run countdown every 10th iteration... Either with a counter or nested loop... But meh
