### ISSUE TITLE
Add pause/resume

### ISSUE THREAD

**Issue by forginater** [forginater/pom_rust#2]
### TODO
- [x] Fix Bug: updating time remaining after emitting "paused message" and successfully pausing
- [x] Fix Bug: If pause close to end of interval, can emit paused message, but then start the next interval negating the pause state
- [x] Clean up the terminal output
- [x] time stamp the countdown messages
- [x] Add Total time
- [x] format time string
- [ ] Fix: When exit terminal due to panic, stays in raw mode 

### Optional
- [ ] Remove buffer message in get_num_from_terminal
- [ ] Make timer loop iteration 1s after reaching 0 remaining

> Could make pause polling more responsive by shortening loop iterations into 100ms and run countdown every 10th iteration... Either with a counter or nested loop... But meh

**Comment by forginater** [comment]
- [x] Fix Bug: updating time remaining after emitting "paused message" and successfully pausing
- [x] Fix Bug: If pause close to end of interval, can emit paused message, but then start the next interval negating the pause state
